### ISSUE TITLE
Mock back-end

### ISSUE THREAD

**Issue by kennethlynne** [EdtechFoundry/edtech-seed-project-fe#29]
Implementer mock back-end for hurtig prototyping

**Comment by kennethlynne** [comment]
https://www.mockable.io !!

**Comment by AlmaasAre** [comment]
https://github.com/js-data/js-data-angular-mocks ?

**Comment by kennethlynne** [comment]
Slik jeg løser det nå for NSB er at jeg lager en Node tjeneste som fungerer som en caching proxy ved at alle spørringer går til den, og om ikke den reelle back-enden svarer innenfor gitt tid/evt. alltid så svarer den med mocks. 

Dette er nødvendig for å kunne stubbe ut alt, også det som skulle skje utenfor angular verden. Jeg kan ta ansvar for denne med lærdom av det jeg gjør fra NSB.

**Comment by kennethlynne** [comment]
Så en egen gulp task fyrer opp proxy, og basert på hvilke flags man startet tasken med så svarer den med mocks eller reelle data.

**Comment by kennethlynne** [comment]
Hva syntes du? En lokal proxyserver som injecter mocks? 

Eksempel:

```
var http = require('http');
var httpProxy = require('http-proxy');
var mocks = require('../core/dist/core');
var director = require('director');
var q = require('q');

var router = new director.http.Router();

var port = process.env.PORT || 13000;
var mocksEnabled = process.env.MOCKS === 'true';
var apiUrl = process.env.API || 'http://138.62.122.145/rest';

var proxy = httpProxy.createProxyServer({});

function jsonResponse(resultStream, obj) {
  resultStream.writeHead(200, {'Content-Type': 'application/json'});
  resultStream.write(JSON.stringify(obj));
  resultStream.end();
};

if (mocksEnabled) {
  // Register mock handlers

  //router.get('/rest/itineraryservices5/reconstructItinerary', function () {
  //  jsonResponse(this.res, {hello: 123}); //TODO: Return mock data
  //});

  router.get('/rest/itineraryservices5/getItineraries', function () {
    var res = this.res;
    jsonResponse(res, Core.Mocks.Networking.Services.getItinerary());
  });

}

var server = http.createServer(function (req, res) {
  router.dispatch(req, res, function (err) {
    if (err.status === 404) {
      // If no overrides (mocks) are defined, forward the request.
      console.log('Forwarding request: ' + req.url);
      proxy.web(req, res, {
        target: apiUrl
      });
    }

    if (err && err.status !== 404) {
      console.log(err.message);
      res.writeHead(500);
      res.end();
    }
  });
});

console.log('Mock server listening on localhost:' + port);
server.listen(port);
```

**Comment by kennethlynne** [comment]
Da har man kontroll på responsen uansett om det er `$http` spørringer eller igjennom noe annet.

**Comment by AlmaasAre** [comment]
Ser cute ut! Kan bli vanskelig å vedlikeholde ser jeg for meg. Men får finne et godt pattern : ) Goodie!

**Comment by AlmaasAre** [comment]
Ser bra ut. Sier aye til å implementere dette!

**Comment by AlmaasAre** [comment]
fixed i PR #51

**Comment by kennethlynne** [comment]
Sweet.  Skal sjekke ut asap

man. 13. apr. 2015, 18:21 skrev Are Almaas <notifications@github.com>:
