### ISSUE TITLE
Sett opp ORM

### ISSUE THREAD

**Issue by kennethlynne** [EdtechFoundry/edtech-seed-project-fe#33]
https://github.com/js-data/js-data 

Veldig interessant siden det er samme ORM for front og back-end, samt at den støtter SQL og MongoDB

Relatert til https://github.com/EdtechFoundry/edtech-seed-project-api/issues/21

**Comment by AlmaasAre** [comment]
Må konfigureres til å bruke samme url-konvensjon som LoopBack.

**Comment by AlmaasAre** [comment]
Loopback standard konvensjon:

create()	POST	/locations
upsert()	PUT	        /locations
exists()	GET	       /locations/:id/exists
findById()	GET	     /locations/:id
find()	GET	     /locations
findOne()	GET	     /locations/findOne
deleteById()	DELETE	/locations/:id
count()	GET	      /locations/count
prototype.updateAttributes()	PUT	/locations/:id
