### ISSUE TITLE
Sett opp autowiring

### ISSUE THREAD

**Issue by kennethlynne** [EdtechFoundry/edtech-seed-project-fe#39]
http://onoffswitch.net/angular-typescript-architecture/

**Comment by AlmaasAre** [comment]
Yeah. Var den jeg siktet til i en shamtale med deg her om dagen. Ser meget cute ut!

**Comment by kennethlynne** [comment]
Ja, tror du sendte meg linken til og med, bare måtte issuifyes ass!

**Comment by AlmaasAre** [comment]
Har en branch med disse endringene nå.
