### ISSUE TITLE
Gjør det lettere å legge inn js filer

### ISSUE THREAD

**Issue by kennethlynne** [EdtechFoundry/edtech-seed-project-fe#43]
Det er vanskelig å ta i bruk seeden til å bruke ren JS.
Noen ting som må fikses:
- [ ] paths.src.scripts -> paths.src.typescripts (så man kan skille på js, ts og evt. annet)
- [ ] legg til en egen mappe for js, og egen mappe for ts som er inkludert i byggsteg/injects

+

**Comment by AlmaasAre** [comment]
Er ikk heeelt sikker på hva du mener? ren JS i UI osv istedenfor typescrpt?

**Comment by kennethlynne** [comment]
Ja, at det må være enklere å bare smelle inn js ja. Nå er det veldig typescript eller go home.

**Comment by AlmaasAre** [comment]
hehe ja. Liker egentlig den tankegangen da. typescript or gtfo. Men hvilke scenarier tenker du da? Hvis man skal inkludere no eksternt js ellerno?

**Comment by kennethlynne** [comment]
Det er kanskje ikke så nøye med denne tasken nei. T(it)S or GTFO. Om man raskt skal prototype noe og smelle sammen noen ferdige rammeverk og ikke gjøre noe særlig custom, så var det iallefall ikke så lett å ta  utgangspunkt i seeden. Well. Det er ikke meningen at vi skal løse alle problemer med seeden. Alt seriøst vi lager mekker vi med TS, lukker sagen for nu

**Comment by AlmaasAre** [comment]
Hm.. Ja, ser jo poenget da.. Just in time js-implementation? Vi må komme igang med å mekke prototype. Kommer sikkert til å støte på en del ting som hindrer fleksibilitet og fortgang etterhvert, men da har vi læææært til neste gang! :dancer:
