### ISSUE TITLE
Restructure CSS (suggestion)

### ISSUE THREAD

**Issue by kennethlynne** [EdtechFoundry/edtech-seed-project-fe#44]
- [ ] crumpify ALL thethings - http://suitedpixel.com/crumpet/

**Comment by kennethlynne** [comment]
@AlmaasAre hva er din mening om dette (for å få igang diskusjonen)

Jeg tror det vil gi mer vedlikeholdbare templates, dog skaper det og mer coupling imellom css selector og template. Jeg tror dog det er lettere å debugge og utvikle med denne approachen.

**Comment by AlmaasAre** [comment]
Ser definitivt veldig flott ut. Men om vi skal f.eks bruke angular-material, så ser jeg ikke helt den umiddelbare nytten? Men det var veldig ryddig da.. Men beslutningen om å bruke angular material er vel kanskje veldig prosjektspesifikt..? Hmm...

Kan jo implementere crumpet i prosjektet, og ser vi bruk for angular material i prosjektet vi jobber i, så bytter vi bare..?

**Comment by kennethlynne** [comment]
Ja sant, bra vi får diskutert litt. Jeg var helt solgt, men det er jo sant at mange andre verktøy ikke er lagt opp til å fungere på samme måten. Når vi benytter oss av andre libs må vi kanskje manuelt crumpifye stilene fra biblioteket. Det er jo enkelt nok, men er ikke sikker på hva som er best, helhetlig. Det er nok best å gjøre det jævla lett å bytte, og at crumpet er default?

**Comment by AlmaasAre** [comment]
my thoughts exactemundo!
