### ISSUE TITLE
Remove angular-material

### ISSUE THREAD

**Issue by kennethlynne** [EdtechFoundry/edtech-seed-project-fe#47]
Not entirely sure if it is supposed to go in the seed?

**Comment by kennethlynne** [comment]
Vil bare diskutere dette altså. Liker angular material og tror igrunn det kan gjøre nytten, bare undrer om det heller er noe vi skal adde as needed. Seeden burde være så fleksibel som mulig. Det kolliderer jo litt med vår mulig ønskede retning for CSS struktur og.

**Comment by kennethlynne** [comment]
@AlmaasAre Hva syntes du?

**Comment by AlmaasAre** [comment]
Ja, jeg er egentlig veldig enig. Med angular-material så bygger designet omtrent kun med direktiver. Det forkludrer jo html'en, og vil si no way back etter du har implementert det. Eller long way back atleast.

**Comment by kennethlynne** [comment]
Yeah, fjerner det jeg!

**Comment by kennethlynne** [comment]
Sendt pr (in progress)
