### ISSUE TITLE
Where to host?

### ISSUE THREAD

**Issue by AlmaasAre** [EdtechFoundry/edtech-seed-project-fe#52]
Bruke s3 til hosting?
http://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A

Så kan vi ha conditional deploys slik at "test"-branchen deployer til test-miljø på s3, og "release"-branchen deployer til prod-miljø på s3.

Følgende miljø foreslår jeg iallfall:
FE: test og prod på S3
API: test og prod på heroku

Vi må bare passe på at det er lett å koordinere deploys til både s3 og heroku da. Kanskje det er lettere med TeamCity..

Så bruker vi bare travis til alt av bygg på API'et og FE. Eller er det kanskje lurt å gå over til teamcity nå med en gang? Kanskje Travis blir litt dyrt i lengden?

**Comment by AlmaasAre** [comment]
Vi må bare starte et sted, så finner vi fort ut hva som funker

**Comment by kennethlynne** [comment]
https://divshot.com ?

**Comment by AlmaasAre** [comment]
Etter 9 sek me research, ser divshot ut til å være et godt alternativ ja! Vi prøver det!

**Comment by AlmaasAre** [comment]
travis-integrasjon også: http://docs.travis-ci.com/user/deployment/divshot/ whuuh
