### ISSUE TITLE
Refactor environment configuration

### ISSUE THREAD

**Issue by AlmaasAre** [EdtechFoundry/edtech-seed-project-fe#59]
Suggest maybe to implement a express wrapper for the application.

This will allow us to:
* isomorphify the application (low pri)
* build up a config file based on the environmental variables where it is hosted. 

On the other hand, we could also create a config file during the build on the CI, but then we would have to have one build configuration for each environment..

Any thoughts on this @kennethlynne ?

**Comment by AlmaasAre** [comment]
Divshot seems to be so OK in the balls, that we have to figure something else out.

**Comment by AlmaasAre** [comment]
Well, kiss me in the face: http://docs.divshot.com/guides/environment-variables

**Comment by kennethlynne** [comment]
#cuteaskittens

**Comment by kennethlynne** [comment]
Did not understand the original issue

**Comment by AlmaasAre** [comment]
What i meant was to streamline control of the environment in both the build-step and in the application itself. The environment for the application should be the same as for build. But pretty much solved with :

http://docs.divshot.com/guides/environment-variables
