### ISSUE TITLE
Add automatic screenshots

### ISSUE THREAD

**Issue by AlmaasAre** [EdtechFoundry/edtech-seed-project-fe#6]
https://github.com/facebookarchive/huxley
vs
https://github.com/sindresorhus/pageres
vs
http://garris.github.io/BackstopJS/

**Comment by AlmaasAre** [comment]
http://davidwalsh.name/visual-regression-testing-angular-applications

**Comment by AlmaasAre** [comment]
Dette er kanskje ikke nødvendig enda? @kennethlynne ?

**Comment by kennethlynne** [comment]
Yeah. Absolutt viktigere å fokusere mer energi på features og funksjonelle tester osv først
