### ISSUE TITLE
Make sure it is super accessible 

### ISSUE THREAD

**Issue by kennethlynne** [EdtechFoundry/edtech-seed-project-fe#61]
http://simplyaccessible.com/article/spangular-accessibility/

**Comment by AlmaasAre** [comment]
Vi burde slenge dette inn i readme ellerno sånt. Som en code-design liksom. Ser for meg at dette blir en task som blir hengende rundt lenge :package:

**Comment by kennethlynne** [comment]
Ja,  det er ikke egentlig en task! Smeller i README jeg
