### ISSUE TITLE
Use html5 routing

### ISSUE THREAD

**Issue by kennethlynne** [EdtechFoundry/edtech-seed-project-fe#64]
http://docs.divshot.com/integrations/angularjs

**Comment by AlmaasAre** [comment]
Ja her må vi ta en schtandpunkt en eller annen gang. 

Skal vi støtte IE9/10? Som kanskje de fleste skoler har på maskinene sine enda.. desverr.

Eller skal vi overbevise BI og co om at en løsning som fokuseres på evergreen-browserne er det beste? Stemmer for evergreen, men det er et viktig business-valg lizzm

**Comment by kennethlynne** [comment]
Jeg tenker at det først og fremst skal se sexy ut og funke bra på nyere nettlesere, samt fokus på smidighet og at det er lett å videreutvikle. Når det blir kjøpt og skal brukes av skoler i større størrelsesorden så kan vi ta en stiling til om vi legger inn en shim for IE10 basert på faktiske brukere. 
Jeg vil heller droppe støtte, og følgelig noen prosenter av brukerene for å kunne fokusere mer på å gjøre det awesome i nyere nettlesere og bruke tiden på ting som tilgjengelighet og features, fremfor browser quirks.

**Comment by kennethlynne** [comment]
Vi lager jo løsninger for *fremtidens* skole. Og jeg nekter å la IE holde oss tilbake. :dancer:

**Comment by AlmaasAre** [comment]
Lager fremtidens løsninger for dagens skoler :D Men dette er noe som kommer til å komme opp, og vi bør ta en liten runde på det med resten av gutta og BI uansett en gang. Men vi smoother den opp til å passe til evergreen-browsere nå da.

"...bruke tiden på ting som tilgjengelighet og features, fremfor browser quirks." Agree!
