### ISSUE TITLE
Add gulp task: SVG-store

### ISSUE THREAD

**Issue by AlmaasAre** [EdtechFoundry/edtech-seed-project-fe#8]
* https://github.com/w0rm/gulp-svgstore

Trenger strengt talt ikke det enda men?..

**Comment by kennethlynne** [comment]
Denne er smud den, men jeg tenker det er noe vi mekker just in time? Usikker på om alle prosjekter trenger SVG nemlig, og det er jo lett nok å legge inn svgstore already

**Comment by AlmaasAre** [comment]
Agreed, close it
